In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
df = pd.read_csv('ab_data.csv')
df.head()

   user_id                   timestamp      group landing_page  converted
0   851104  2017-01-21 22:11:48.556739    control     old_page          0
1   804228  2017-01-12 08:01:45.159739    control     old_page          0
2   661590  2017-01-11 16:55:06.154213  treatment     new_page          0
3   853541  2017-01-08 18:28:03.143765  treatment     new_page          0
4   864975  2017-01-21 01:52:26.210827    control     old_page          1

In [3]:
df.shape

(294478, 5)

In [4]:
df['converted'].mean()

np.float64(0.11965919355605512)

In [6]:
df.nunique()

user_id         290584
timestamp       294478
group                2
landing_page         2
converted            2
dtype: int64

In [7]:
df.query('group == "treatment" and landing_page != "new_page"')

        user_id                   timestamp      group landing_page  converted
308      857184  2017-01-20 07:34:59.832626  treatment     old_page          0
327      686623  2017-01-09 14:26:40.734775  treatment     old_page          0
357      856078  2017-01-12 12:29:30.354835  treatment     old_page          0
685      666385  2017-01-23 08:11:54.823806  treatment     old_page          0
713      748761  2017-01-10 15:47:44.445196  treatment     old_page          0
...         ...                         ...        ...          ...        ...
293773   688144  2017-01-16 20:34:50.450528  treatment     old_page          1
293817   876037  2017-01-17 16:15:08.957152  treatment     old_page          1
293917   738357  2017-01-05 15:37:55.729133  treatment     old_page          0
294014   813406  2017-01-09 06:25:33.223301  treatment     old_page          0
294252   892498  2017-01-22 01:11:10.463211  treatment     old_page          0

[1965 rows x 5 columns]

In [8]:
df.query('group == "control" and landing_page != "old_page"')

        user_id                   timestamp    group landing_page  converted
22       767017  2017-01-12 22:58:14.991443  control     new_page          0
240      733976  2017-01-11 15:11:16.407599  control     new_page          0
490      808613  2017-01-10 21:44:01.292755  control     new_page          0
846      637639  2017-01-11 23:09:52.682329  control     new_page          1
850      793580  2017-01-08 03:25:33.723712  control     new_page          1
...         ...                         ...      ...          ...        ...
293894   741581  2017-01-09 20:49:03.391764  control     new_page          0
293996   942612  2017-01-08 13:52:28.182648  control     new_page          0
294200   928506  2017-01-13 21:32:10.491309  control     new_page          0
294253   886135  2017-01-06 12:49:20.509403  control     new_page          0
294331   689637  2017-01-13 11:34:28.339532  control     new_page          0

[1928 rows x 5 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294478 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       294478 non-null  int64
 1   timestamp     294478 non-null  object
 2   group         294478 non-null  object
 3   landing_page  294478 non-null  object
 4   converted     294478 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.2+ MB

In [10]:
df2t = df.query('group == "treatment" and landing_page != "new_page"')
df2c = df.query('group == "control" and landing_page != "old_page"')

In [11]:
df2 = df2t.merge(df2c, how='outer')
df2.head()

   user_id                   timestamp      group landing_page  converted
0   630052  2017-01-07 12:25:54.089486  treatment     old_page          1
1   630126  2017-01-14 13:35:54.778695  treatment     old_page          0
2   630137  2017-01-22 14:59:22.051308    control     new_page          0
3   630320  2017-01-12 05:27:37.181803  treatment     old_page          0
4   630471  2017-01-07 02:14:17.405726    control     new_page          0

In [12]:
df2.shape

(3893, 5)

In [13]:
df2.describe()

             user_id    converted
count    3893.000000  3893.000000
mean   785682.547906     0.124326
std     90159.968183     0.329995
min    630052.000000     0.000000
25%    708538.000000     0.000000
50%    783362.000000     0.000000
75%    864749.000000     0.000000
max    945971.000000     1.000000

In [14]:
df2.nunique()

user_id         3893
timestamp       3893
group              2
landing_page       2
converted          2
dtype: int64

In [15]:
sum(df2['user_id'].duplicated())

0

In [16]:
df2.converted.mean() * 100

np.float64(12.432571281787824)

In [17]:
df2_control = df2.query('group == "control"')
df2_treamrment = df2.query('group == "treatment"')

In [18]:
df2_control['converted'].mean() * 100

np.float64(12.136929460580912)

In [19]:
df2_treamrment['converted'].mean() * 100

np.float64(12.72264631043257)

In [20]:
df2['converted'].mean()

np.float64(0.12432571281787824)

In [21]:
1 - df2['converted'].mean()

np.float64(0.8756742871821217)