In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import math
import pickle

In [2]:
df = pd.read_csv('orange_trees.csv')
df.head()

   tree_number     oranges
0         1223  305.470796
1         1224  208.357224
2         1225  318.145987
3         1226  274.531146
4         1227  245.627474

In [3]:
df.describe()

       tree_number     oranges
count    133.00000  133.000000
mean    1289.00000  277.852803
std       38.53786   50.922243
min     1223.00000  137.023145
25%     1256.00000  237.696112
50%     1289.00000  279.470482
75%     1322.00000  312.079787
max     1355.00000  434.025714

In [4]:
population_mean = 271.93

In [5]:
stats.ttest_1samp(a = df['oranges'], popmean=population_mean)

TtestResult(statistic=np.float64(1.3413606837344207), pvalue=np.float64(0.18210666026278088), df=np.int64(132))

In [6]:
population_mean = 3.2
type(population_mean)

float