In [1]:
import pandas as pd
import numpy as np
import imblearn

In [2]:
data = pd.read_csv('aug_test.csv')
data.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage
0,57782,Female,34,1,39.0,1,1-2 Year,No,38244.0,124.0,146
1,286811,Female,55,1,28.0,0,> 2 Years,Yes,37577.0,122.0,109
2,117823,Male,39,1,28.0,1,1-2 Year,No,24578.0,26.0,63
3,213992,Male,28,1,50.0,1,1-2 Year,No,40507.0,8.0,129
4,324756,Female,24,1,10.0,0,< 1 Year,Yes,36783.0,152.0,201

In [4]:
data.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage'],
      dtype='object')

In [5]:
data.describe()

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage
count,78273.000000,78273.000000,78273.000000,78273.000000,78273.000000,78273.000000,78273.000000,78273.000000
mean,233993.913827,38.507570,0.997866,26.381434,0.488917,30707.042441,111.993216,154.827220
std,139265.743227,15.216589,0.046141,13.149780,0.499880,17044.185877,54.270018,83.476632
min,2.000000,20.000000,0.000000,0.000000,0.000000,2630.000000,1.000000,10.000000
25%,115579.000000,25.000000,1.000000,15.000000,0.000000,24548.000000,26.000000,83.000000
50%,229110.000000,36.000000,1.000000,28.000000,0.000000,31741.000000,150.000000,155.000000
75%,344739.000000,49.000000,1.000000,35.000000,1.000000,39476.000000,152.000000,227.000000
max,508136.000000,85.000000,1.000000,52.000000,1.000000,489663.000000,163.000000,299.000000

In [9]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [7]:
X = data.iloc[:, 2:]
X.head()

,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage
0,34,1,39.0,1,1-2 Year,No,38244.0,124.0,146
1,55,1,28.0,0,> 2 Years,Yes,37577.0,122.0,109
2,39,1,28.0,1,1-2 Year,No,24578.0,26.0,63
3,28,1,50.0,1,1-2 Year,No,40507.0,8.0,129
4,24,1,10.0,0,< 1 Year,Yes,36783.0,152.0,201