In [2]:
import pandas as pd

In [13]:
df = pd.read_csv("per.csv", sep="\t", header=None, engine="python")
df = df.drop(columns=[0])
df.columns = ["title", "category", "label"]
df.head()

                                               title     category     label
0                                            content        label  label_id
1  حسن جوهرچی بازیگر سینما و تلویزیون ایران در گف...  فرهنگی هنری         5
2  به گزارش گروه بین الملل باشگاه خبرنگاران جوان ...    بین الملل         2
3  به گزارش خبرنگار فوتبال و فوتسال گروه ورزشی با...        ورزشی         6
4  به‌ گزارش گروه اقتصادی باشگاه خبرنگاران به نقل...      اقتصادی         1

In [ ]:
with open('stopwords.txt', encoding='utf8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n','') for line in stopwords]
stopwords

['﷼',
 '\u200f\u200f\u200fعلاقه مند',
 '\u200fیاب',
 '\u200fگیر',
 '\u200fگوی',
 '\u200fکن',
 '\u200fشو',
 '\u200fدیگران',
 '\u200fدار',
 '\u200fخواه',
 '\u200fتوان',
 '\u200fباش',
 '\u200fآی',
 '\u200fآور',
 'یکی',
 'یکهزار',
 'یکسال',
 'یکریز',
 'یکدیگر',
 'یک کمی',
 'یک کم',
 'یک چیزی',
 'یک جوری',
 'یک',
 'یواش یواش',
 'یواش',
 'یو',
 'یه',
 'یكی',
 'یكپارچه',
 'یكنواخت',
 'یكطرفه',
 'یكسری',
 'یكسره',
 'یكسال',
 'یكزمان',
 'یكریز',
 'یكدیگر',
 'یكدیر',
 'یكدم',
 'یكجوری',
 'یكجور',
 'یكجانبه',
 'یكجا',
 'یكباره',
 'یكبار',
 'یكایك',
 'یك',
 'یقیناً',
 'یقینا',
 'یعنی',
 'یشتری',
 'یشتر',
 'یش',
 'یست',
 'یری',
 'یرونِ',
 'یرد',
 'یافتیم',
 'یافتید',
 'یافتی',
 'یافته',
 'یافتن',
 'یافتم',
 'یافت',
 'یارب',
 'یاد',
 'یابیم',
 'یابید',
 'یابی',
 'یابند',
 'یابم',
 'یابد',
 'یاب',
 'یااینكه',
 'یاانكه',
 'یااز',
 'یا',
 'ی',
 'گیریم',
 'گیرید',
 'گیری',
 'گیرند',
 'گیرم',
 'گیرد',
 'گیر',
 'گيري',
 'گيرد',
 'گوییم',
 'گویید',
 'گویی',
 'گویند',
 'گویم',
 'گوید',
 'گویان',
 'گویا',
 'گوی',
 'گويند',
 'گويد',
 'گونه',
 'گو',
 'گهگاهی',
 'گهگاه',
 'گه',
 'گمان',
 'گفتیم',
 'گفتید',
 'گفتی',
 'گفته',
 'گفتند',
 'گفتن',
 'گفتم',
 'گفت',
 'گرچه',
 'گروهی',
 'گروهي',
 'گرنه',
 'گرمی',
 'گرفتیم',
 'گرفتید',
 'گرفتی',
 'گرفته',
 'گرفتند',
 'گرفتن',
 'گرفتم',
 'گرفتارند',
 'گرفت',
 'گردید',
 'گردند',
 'گردد',
 'گر',
 'گذشته',
 'گذاشتیم',
 'گذاشته',
 'گذاشتن',
 'گذاری',
 'گذاري',
 'گذاران',
 'گاهی',
 'گاه',
 'گ',
 'کی',
 'کَی',
 'کو',
 'که',
 'کنیم',
 'کنید',
 'کنی',
 'کنونی',
 'کنون',
 'کنه',
 'کننده',
 'کنند',
 'کنن',
 'کنم',
 'کند',
 'کنایه\u200cای',
 'کنان',
 'کنارِ',
 'کنارش',
 'کنار',
 'کن',
 'کمی',
 'کمک',
 'کمتری',
 'کمتره',
 'کمتر',
 'کماکان',
 'کما\x7fاینکه',
 'کم کم',
 'کم',
 'کلیه',
 'کلی',
 'کلا',
 'کل',
 'کسی',
 'کسانی',
 'کس',
 'کردین',
 'کردیم',
 'کردید',
 'کردی',
 'کرده',
 'کردند',
 'کردن',
 'کردم',
 'کرد',
 'کرات',
 'کدام',
 'کجاست',
 'کجا',
 'کتبا',
 'کاملاً',
 'کاملا',
 'کامل',
 'کاشکی',
 'کاش',
 'کارند',
 'کار',
 'کا',
 'ک',
 'ژ',
 'چیه',
 'چیست',
 'چیزیست',
 'چیزی',
 'چیزهاست',
 'چیز',
 'چی',
 'چگونه',
 'چکار',
 'چيزي',
 'چونه',
 'چون',
 'چو',
 'چهارهزار',
 'چهار',
 'چه طور',
 'چه بسا',
 'چه',
 'چنین',
 'چنين',
 'چندین',
 'چنده',
 'چندمین',
 'چندماهه',
 'چندروزه',
 'چندانی',
 'چندان',
 'چند روزه',
 'چند',
 'چنانکه',
 'چنانچه',
 'چنانكه',
 'چنان',
 'چكار',
 'چقدر',
 'چطور',
 'چشم بسته',
 'چشم',
 'چراكه',
 'چرا که',
 'چرا',
 'چته',
 'چت',
 'چاپلوسانه',
 'چاله',
 'چارده',
 'چ',
 'پیگیر',
 'پیوسته',
 'پیشِ',
 'پیششون',
 'پیشتر',
 'پیشاپیش',
 'پیش',
 'پیرامون',
 'پیدرپی',
 'پیداست',
 'پیدا',
 'پیامبرانه',
 'پی درپی',
 'پی',
 'پيش',
 'پهن شده',
 'پهن',
 'په',
 'پنهان',
 'پنج',
 'پشیمونی',
 'پشتوانه اند',
 'پشتوانه',
 'پشت',
 'پس فردا',
 'پس از',
 'پس',
 'پریروز',
 'پروردگارا',
 'پرسان',
 'پراز',
 'پذیرند',
 'پذیر',
 'پدیده',
 'پدرپی',
 'پدرانه',
 'پایین ترند',
 'پایین',
 'پاعینِ',
 'پاره\u200cای',
 'پاره',
 'پارسایانه',
 'پارسال',
 'پ',
 '٪',
 'ّه',
 'يكي',
 'يكديگر',
 'يك',
 'يابد',
 'يا',
 'ویژه',
 'ویند',
 'وید',
 'ویا',
 'وی',
 'وگو',
 'وگرنه',
 'وگرد',
 'وگر',
 'وي',
 'وهمین',
 'ونن',
 'ولیكن',
 'ولی',
 'وقتیکه',
 'وقتیكه',
 'وقتی که',
 'وقتی',
 'وقتي',
 'وضوح',
 'وضع',
 'وسطِ',
 'وزو',
 'ورای',
 'ورا',
 'ور',
 'وده',
 'ودند',
 'ودن',
 'ود',
 'وحشت زده',
 'وحشت',
 'وجودیكه',
 'وجود',
 'وجه',
 'وجدانا',
 'وبرای',
 'وای',
 'واما',
 'واقفند',
 'واقعی',
 'واقعاً',
 'واقعا',
 'واقع',
 'واضحتر',
 'واضح',
 'واسه',
 'واسش',
 'وارد',
 'وابسته اند',
 'وابسته',
 'و لا غیر',
 'و',
 'هیچ\u200cجور',
 'هیچیك',
 'هیچی',
 'هیچگونه',
 'هیچگاه',
 'هیچکس',
 'هیچکدام',
 'هیچوقت',
 'هیچكس',
 'هیچكدام',
 'هیچجور',
 'هیچ گاه',
 'هیچ جور',
 'هیچ',
 'هی',
 'هيچ',
 'هوی',
 'هوشیارانه',
 'هوشمندانه',
 'هنگامیكه',
 'هنگامی که',
 'هنگامی',
 'هنگامِ',
 'هنگام',
 'هنوز',
 'هنامی',
 'هنامِ',
 'هنام',
 'همینكه',
 'همینطوریكه',
 'همینطوری',
 'همینطوركه',
 'همینطور',
 'همین که',
 'همین',
 'همیشگی',
 'همیشه',
 'همی',
 'همگی',
 'همگان',
 'همگام',
 'همچین',
 'همچون',
 'همچنین',
 'همچنين',
 'همچنانكه',
 'همچنان که',
 'همچنان',
 'همين',
 'همون',
 'همواره',
 'همه\u200cمون',
 'همه\u200cاش',
 'همهٌ',
 'همه مون',
 'همه شان',
 'همه ساله',
 'همه روزه',
 'همه',
 'همنوا',
 'هممون',
 'همكارانه',
 'همسوبا',
 'همسو',
 'همزمان',
 'همدیگر',
 'همدلانه',
 'همخوان',
 'هماهنگتر',
 'همانی',
 'همانها',
 'همانند',
 'همانقدر',
 'همانطوریكه',
 'همانطوری',
 'همانطوركه',
 'همانطور',
 'همانا',
 'همان گونه که',
 'همان طور که',
 'همان',
 'هم اینک',
 'هم اکنون',
 'هم',
 'هق هق کنان',
 'هق',
 'هفت',
 'هشیارانه',
 'هشان',
 'هسن',
 'هستیم',
 'هستید',
 'هستی',
 'هستيم',
 'هستند',
 'هستن',
 'هستم',
 'هستش',
 'هستا',
 'هست',
 'هزارها',
 'هزار',
 'هرگونه',
 'هرگز',
 'هرگاه',
 'هرکی',
 'هرکس',
 'هرچه',
 'هرچند',
 'هرچقدر',
 'هروقت',
 'هركه',
 'هركسی',
 'هركس',
 'هركدام',
 'هرقدر',
 'هرساله',
 'هرزچندگاهی',
 'هرز',
 'هرحال',
 'هرجا',
 'هرانچه',
 'هرازچندگاهی',
 'هر چه',
 'هر چند که',
 'هر چند',
 'هر از گاهی',
 'هر',
 'هدف',
 'هترین',
 'هبچ',
 'هایی',
 'هایت',
 'های',
 'هايي',
 'هاي',
 'هانتا',
 'هان',
 'هامو',
 'هام رو',
 'هاش',
 'هاست',
 'ها',
 'ه',
 'نیمی',
 'نیم',
 'نیك',
 'نیستیم',
 'نیستند',
 'نیستم',
 'نیست',
 'نیز',
 'نیازمندند',
 'نیازمندانه',
 'نگو',
 'نگاه',
 'نکنیم',
 'نکنید',
 'نکنی',
 'نکنند',
 'نکنم',
 'نکند',
 'نکن',
 'نکرده',
 'نکردن',
 'نيست',
 'نيز',
 'نومید',
 'نوعی',
 'نوعي',
 'نوعاً',
 'نوعا',
 'نوع',
 'نوشت',
 'نود',
 'نواورانه',
 'نهایتاً',
 'نهایتا',
 'نهایت',
 'نهان',
 'نه تنها',
 'نه',
 'نمی\u200cکند',
 'نمی\u200cشود',
 'نمیگیرند',
 'نمیمونید',
 'نمیكنند',
 'نمیكنن',
 'نمیشه',
 'نمیروم',
 'نمیتونه',
 'نمیبرد',
 'نمیاورم',
 'نمی',
 'نمي',
 'نموده',
 'نمایش',
 'نماید',
 'نمايد',
 'نكنه',
 'نكنند',
 'نكرده',
 'نقادانه',
 'نفهمی',
 'نفرند',
 'نفر',
 'نظیر',
 'نظير',
 'نظربه',
 'نظرا',
 'نشون',
 'نشه',
 'نشده',
 'نشان',
 'نسبتا',
 'نسبت',
 'نزدیکِ',
 'نزدیک',
 'نزدیم',
 'نزدیكِ',
 'نزدیكتر',
 'نزدیك',
 'نزدِ',
 'نزديك',
 'نزد',
 'نریم',
 'نره',
 'نرمی',
 'نرم',
 'ندیدی',
 'ندی',
 'ندرتا',
 'ندرت',
 'نداشتیم',
 'نداشتید',
 'نداشتی',
 'نداشته',
 'نداشتند',
 'نداشتم',
 'نداشت',
 'نداریم',
 'ندارید',
 'نداری',
 'نداره',
 'ندارند',
 'ندارم',
 'ندارد',
 'نداد',
 'نخودی',
 'نخواهیم',
 'نخواهید',
 'نخواهی',
 'نخواهند',
 'نخواهم',
 'نخواهد',
 'نخستین',
 'نخستين',
 'نخست',
 'نحوه',
 'نتیجتا',
 'نبود',
 'نبش',
 'نباید',
 'نبايد',
 'نباش',
 'ناید',
 'ناگهانی',
 'ناگهان',
 'ناگزیر',
 'ناگاه',
 'ناچار',
 'ناپذیر',
 'ناهشیار',
 'نام',
 'ناكام',
 'ناشی',
 'ناشي',
 'ناشناخته',
 'ناسازگارانه',
 'ناراین',
 'ناراضی اند',
 'ناراضی',
 'نادیده',
 'ناخوانده',
 'ناخواسته',
 'ناتوان',
 'نااگاهانه',
 'ناامید',
 'نا',
 'ن',
 'می\u200cکنیم',
 'می\u200cکنند',
 'می\u200cکنم',
 'می\u200cکند',
 'می\u200cفرماید',
 'می\u200cشوند',
 'می\u200cشود',
 'می\u200cشد',
 'می\u200cرود',
 'می\u200cرسد',
 'می\u200cدهد',
 'می\u200cداند',
 'می\u200cخواهیم',
 'می\u200cتوانند',
 'می\u200cتواند',
 'می\u200cتوان',
 'می\u200cباشند',
 'می\u200cباشد',
 'می\u200cآید',
 'میگیره',
 'میگی',
 'میگه',
 'میگن',
 'میگم',
 'میگردد',
 'میکنیم',
 'میکنید',
 'میکنی',
 'میکنه',
 'میکنند',
 'میکنن',
 'میکنم',
 'میکند',
 'میکرد',
 'مینوشند',
 'میلیون',
 'میلیارد',
 'میكنیم',
 'میكنه',
 'میكنند',
 'میكنن',
 'میكنم',
 'میكند',
 'میفرستین',
 'میفرستی',
 'میفرستم',
 'میشوند',
 'میشود',
 'میشه',
 'میشم',
 'میشد',
 'میزان',
 'میروم',
 'میره',
 'میرن',
 'میرم',
 'میدهیم',
 'میدهم',
 'میدهد',
 'میده',
 'میدن',
 'میدم',
 'میداد',
 'میخونید',
 'میخونم',
 'میخوای',
 'میخواهند',
 'میخوانید',
 'میخوانم',
 'میخواستن',
 'میخواد',
 'میتونه',
 'میباشد',
 'میان',
 'میاد',
 'می خوانید',
 'می خوانم',
 'می',
 'مگو',
 'مگه',
 'مگراینكه',
 'مگرانكه',
 'مگر این که',
 'مگر آن که',
 'مگر',
 'مکرراً',
 'مکرر',
 'ميليون',
 'ميليارد',
 'مي',
 'مون',
 'موقعیكه',
 'موقتا',
 'موضوع',
 'مورد',
 'موخر',
 'موجودند',
 'موجب',
 'موارد',
 'مواجهند',
 'مهمتره',
 'منی',
 'منو',
 'منم',
 'منطقی',
 'منطقا',
 'منصفانه',
 'مند',
 'منحصربفرد',
 'منحصرا',
 'منحصر',
 'منتهی',
 'من',
 'ممیزیهاست',
 'ممکن',
 'ملیون',
 'ملیارد',
 'ملزم',
 'مكررا',
 'مكرر',
 'مقلوب',
 'مقصری',
 'مقصرند',
 'مقصر',
 'مقدار',
 'مقال',
 'مقابل',
 'مفیدند',
 'مغلوب',
 'مغرضانه',
 'معمولی',
 'معمولاً',
 'معمولا',
 'معلومه',
 'معلق',
 'معذوریم',
 'معدود',
 'معتقدیم',
 'معتقدند',
 'معتقدم',
 'مع ذلک',
 'مع الاسف',
 'مع',
 'مطمینا',
 'مطمنا',
 'مطمانم',
 'مطمانا',
 'مطلقا',
 'مطلق',
 'مشكلتر',
 'مشكل',
 'مشغولند',
 'مشغول',
 'مشخص',
 'مشترکاً',
 'مشتركا',
 'مشت',
 'مسیولانه',
 'مسلما',
 'مسلم',
 'مستند',
 'مستمرا',
 'مستمر',
 'مستقیما',
 'مستقیم',
 'مستقلا',
 'مستعد',
 'مستحضرید',
 'مرسی',
 'مردم اند',
 'مردم',
 'مردانه',
 'مرتبا',
 'مرتب',
 'مراتب',
 'مرا',
 'مر',
 'مذهبی اند',
 'مذهبی',
 'مدّتی',
 'مدتی',
 'مدتهاست',
 'مدت',
 'مدبرانه',
 'مدبر',
 'مداوم',
 'مدام',
 'مخصوصاً',
 'مخصوصا',
 'مختلف',
 'مختصرا',
 'مختصر',
 'مخالفند',
 'محکم\u200cتر',
 'محکم',
 'محكم',
 'محض رضای خدا',
 'محتاطانه',
 'محتاط',
 'محتاجند',
 'مجموعاً',
 'مجموعا',
 'مجموع',
 'مجرمانه',
 'مجدداً',
 'مجددا',
 'مجبورند',
 'مجانی',
 'مثلِ',
 'مثلا',
 'مثل اینکه',
 'مثل',
 'مثابه',
 'متوسفانه',
 'متوالی',
 'متقابلا',
 'متفكرانه',
 'متفاوتند',
 'متعاقبا',
 'متاسفانه',
 'متؤسفانه',
 'مبادا',
 'مایی',
 'ماهیتا',
 'ماهرانه',
 'ماه',
 'مانندِ',
 'مانند',
 'مان',
 'مامان مامان گویان',
 'مامان',
 'مالامال',
 'مالا',
 'ماقبل',
 'ماشینوار',
 'ماست',
 'مارو',
 'مادامیكه',
 'مادامی',
 'مادام',
 'مات',
 'ما رو',
 'ما',
 'م',
 'لیکن',
 'لیكن',
 'لی',
 'لکه',
 'له',
 'لكه',
 'لطفاً',
 'لطفا',
 'لزوماً',
 'لزوما',
 'لذا',
 'لب',
 'لاجرم',
 'لااقل',
 'لا',
 'ل',
 'كیست',
 'كی',
 'كَی',
 'كوركورانه',
 'كودكانه',
 'كه',
 'كنیم',
 'كنید',
 'كنی',
 'كنيم',
 'كنيد',
 'كنه',
 'كننده',
 'كنند',
 'كنن',
 'كنم',
 'كند',
 'كنایه',
 'كنان',
 'كنارِ',
 'كنارش',
 'كنار',
 'كمی',
 'كمتره',
 'كمتر',
 'كماكان',
 'كمابیش',
 'كم',
 'كلیشه',
 'كلی',
 'كلا',
 'كل',
 'كشیدن',
 'كسی',
 'كسي',
 'كسانی',
 'كس',
 'كزین',
 'كز',
 'كردیم',
 'كردید',
 'كرده',
 'كردند',
 'كردن',
 'كردم',
 'كرد',
 'كرات',
 'كدامیك',
 'كدامند',
 'كدام',
 'كجاست',
 'كجا',
 'كاین',
 'كان',
 'كاملتر',
 'كاملا',
 'كاشكی',
 'كاش',
 'كارند',
 'كاربرمدارانه',
 'كارافرینانه',
 'ك',
 'قیلا',
 'قل',
 'قطعاً',
 'قطعا',
 'قضایاست',
 'قصدِ',
 'قریب',
 'قراردادن',
 'قرار',
 'قدری',
 'قدرمسلم',
 'قدر',
 'قد',
 'قبلند',
 'قبلاً',
 'قبلا',
 'قبل',
 'قانوناً',
 'قانونا',
 'قال',
 'قاعدتاً',
 'قاعدتا',
 'قاطعانه',
 'قاطبه',
 'قابل',
 'قاالند',
 'ق',
 'فی',
 'فکر',
 'فوق',
 'فوری',
 'فورا',
 'فهرستوار',
 'فناورانه',
 'فلذا',
 ...]

In [5]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Amir\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

2633

In [7]:
from parsivar import FindStems
stemmer = FindStems()

In [9]:
stemmer.convert_to_stem('کتاب ها')

'کتاب'

In [10]:
from parsivar import Tokenizer

In [ ]:
from parsivar import Tokenizer, FindStems
import pandas as pd

tokenizer = Tokenizer()
stemmer = FindStems()

dataset = pd.DataFrame(columns=('title_body', 'category'))

for index, row in df.iterrows():
    text = row['title'] 
    tokens = tokenizer.tokenize_words(text)
    tokens_filtered = [w for w in tokens if w not in stopwords]
    tokens_stemmed = [stemmer.convert_to_stem(w) for w in tokens_filtered]

    dataset.loc[index] = {
        'title_body': ' '.join(tokens_stemmed),
        'category': row['category']
    }

In [18]:
dataset.head()

                                          title_body     category
0                                            content        label
1  حسن جوهر بازیگر سینما تلویزیون ایران گفتگو خبر...  فرهنگی هنری
2  گزارش گروه الملل باشگاه خبرنگار جوان نقل هیل، ...    بین الملل
3  گزارش خبرنگار فوتبال فوتسال گروه ورزشی باشگاه ...        ورزشی
4  گزارش گروه اقتصادی باشگاه خبرنگار نقل پایگاه ا...      اقتصادی

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [21]:
X = vectorizer.transform(dataset['title_body'])

In [22]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 208902 stored elements and shape (1645, 24102)>

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [25]:
le.classes_

array(['label', 'اجتماعی', 'اقتصادی', 'بین الملل', 'سیاسی', 'علمی فناوری',
       'فرهنگی هنری', 'ورزشی', 'پزشکی'], dtype=object)

In [26]:
len(y)

1645

In [27]:
import numpy as np

In [28]:
print(np.unique(dataset['category']))

['label' 'اجتماعی' 'اقتصادی' 'بین الملل' 'سیاسی' 'علمی فناوری'
 'فرهنگی هنری' 'ورزشی' 'پزشکی']

In [30]:
np.shape(X)

(1645, 24102)

In [31]:
np.shape(y)

(1645,)

In [32]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [35]:
from sklearn import svm

In [36]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [37]:
svmc.score(X_test, y_test)

0.8009708737864077

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)

In [40]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.65      0.74      0.69        47
           2       0.81      0.76      0.78        38
           3       0.84      0.81      0.83        53
           4       0.69      0.62      0.65        50
           5       0.74      0.91      0.82        58
           6       0.90      0.90      0.90        58
           7       1.00      0.83      0.91        41
           8       0.85      0.79      0.82        67

    accuracy                           0.80       412
   macro avg       0.81      0.80      0.80       412
weighted avg       0.81      0.80      0.80       412